name: Training Workflow
on:
  workflow_dispatch:
    inputs:
      script_content:
        description: 'Content of train.py'
        required: true
        type: string

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install uv
        uses: astral-sh/setup-uv@v1

      - name: Create virtual environment and install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install --no-deps numpy torch
          
      - name: Create and run training script
        run: |
          echo "${{ inputs.script_content }}" > train.py
          source .venv/bin/activate
          python train.py > training.log 2>&1
        
      - name: Upload logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: training-logs
          path: training.log