name: Training Workflow
on:
  workflow_dispatch:
    inputs:
      script_content:
        description: 'Content of train.py'
        required: true
        type: string

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache PyTorch
        uses: actions/cache@v3
        id: pytorch-cache
        with:
          path: |
            ~/.cache/pip
            ~/.cache/torch
            ~/.cache/torch_extensions
          key: ${{ runner.os }}-pytorch-${{ hashFiles('requirements.txt') }}-v1
          restore-keys: |
            ${{ runner.os }}-pytorch-

      - name: Install dependencies
        run: |
          pip install torch
          pip install numpy

      - name: Create and run training script
        run: |
          echo "${{ inputs.script_content }}" > train.py
          cat train.py  # Debug: print the content
          python train.py > training.log 2>&1
        
      - name: Upload logs
        uses: actions/upload-artifact@v3
        if: always()  # Upload logs whether the job succeeds or fails
        with:
          name: training-logs
          path: training.log